### PR TITLE
Proposed fix to follow the same behaviour as Tomcat for static imports

### LINKED ISSUE #239: Missing static imports with Expression Language expressions
With the changes made for pages 3.1 making the imports in a jsp available to the EL scripting language, ran the following jsp to verify static imports 
```jsp
<%@ page import = "static myapp.Example.STATIC_VAR, static myapp.Example.STATIC_METHOD" %>
<html>
   <head>
      <title>Import Static</title>
   </head>
   
   <body>
      EL expressions: <br/>
      ${STATIC_VAR}
      ${STATIC_METHOD()}

      <br/>
      <br/>
      
      JSP expressions: <br/>
      <%=STATIC_VAR%>
      <%=STATIC_METHOD()%>
   </body>
</html>
```

The JSP expressions resolve as expected but of the EL expressions, only STATIC_METHOD() works. Using the Tomcat JSP API all expressions resolve as expected.

See also Tomcat issue https://bz.apache.org/bugzilla/show_bug.cgi?id=66441

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #239
Based off Tomcat JSP API with static imports

### CODE REVIEW

**Comment by markt-asf** [comment]
There is a potential licensing issue here. The change in this PR appears to have been copied from the Tomcat source code. The ALv2 allows that but it requires some hoop jumping to sort out the paperwork on the Eclipse side and to ensure the correct license information appears in the source code.
However, since I wrote the original code for Tomcat that has been copied here, as long as I agree to contribute that code under my ECA (I do) then we can avoid the hoop jumping.
Note to self, this needs to be merged into 3.1.x and master.

**Comment by isaacrivriv** [comment]
Thanks for clarifying @markt-asf

**Comment by isaacrivriv** [comment]
If this gets accepted or something similar gets merged in, will a new jar be built for 3.1.x?

**Comment by joakime** [comment]
@markt-asf not sure how to get this approved from Eclipse Legal point of view.

Let's get @waynebeaton to chime in.

**Comment by isaacrivriv** [comment]
FYI @waynebeaton

**Comment by markt-asf** [comment]
I'm happy there are no legal issues here as long as I do the commit since I own the copyright to that particular bit of code. I intend to proceed shortly (once I make sure I have the right branches checked out locally).

**Comment by markt-asf** [comment]
For clarity, I've opened #241 to address this in master. I'll then back-port to 3.1.x.

**Comment by isaacrivriv** [comment]
Thanks for getting the fix in @markt-asf! After the back-port, will a new 3.1.x jar be created and published?

**Comment by markt-asf** [comment]
Yes - just need to read up on the hoops I have to jump through to do that. From memory, a bug fix like this doesn't require much (any?) paperwork but I want to make sure I follow the correct process.
I have the fix ready to push but I want to add something along the lines of a release note to the repo first so folks can easily find out what fixes are in what point release without having to dig through the commit log.

**Comment by isaacrivriv** [comment]
That's great news, thanks a lot Mark!!

**Comment by markt-asf** [comment]
Try the 3.1.1 JAR from the staging repo:
https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.1.1/

If that works for you then I'll release it to Maven Central.

**Comment by arjantijms** [comment]
@markt-asf thanks! +1 from me for that.

**Comment by isaacrivriv** [comment]
The jar works for me, thanks @markt-asf!!

**Comment by markt-asf** [comment]
Released. Should be on Maven Central shortly.

**Comment by waynebeaton** [comment]
> @markt-asf not sure how to get this approved from Eclipse Legal point of view.

Mark's assessment is correct.

> The ALv2 allows that but it requires some hoop jumping to sort out the paperwork on the Eclipse side and to ensure the correct license information appears in the source code.

Its not so much _hoop jumping_ as it that the Eclipse Foundation has services and resources that we provide to our open source project teams to help them navigate potentially tricky intellectual property issues.

However, as I stated, as the copyright holder, Mark has all of the necessary rights to make this contribution.

**Pull request closed without merging**
