### PR TITLE
Fix #245 - caching to avoid repeat ImportHandler.resolveClass calls

### LINKED ISSUE #245: Performance issues from repeating ImportHandler.resolveClass calls for null attributes
This is an issue like https://bz.apache.org/bugzilla/show_bug.cgi?id=57583 that I currently reproduce on EAP 7.4 (using pages 2.3.x) and EAP 8.0 (using pages 3.1.x).  An easy stress test is a jsp referring to many null attributes:
`<td><p style="color: red">${error1}</p></td>
\<td><p style="color: red">${error2}</p></td>
...
\<td><p style="color: red">${error999}</p></td>
\<td><p style="color: red">${error1000}</p></td>`

This performs much worse (10-20x longer) on EAP 7/8 where the ImportHandler is now used compared to EAP 6 that did not .  Requests spend all their time in Class.forName calls from the ImportHandler:
`"default task-10" #157 prio=5 os_prio=0 cpu=2098.07ms elapsed=21.51s tid=0x0000562376ddf800 nid=0x37ded runnable  [0x00007f15ab838000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Class.forName0(java.base@11.0.20/Native Method)
	at java.lang.Class.forName(java.base@11.0.20/Class.java:398)
	at jakarta.el.ImportHandler.getClassFor(ImportHandler.java:169)
	at jakarta.el.ImportHandler.resolveClassFor(ImportHandler.java:145)
	at jakarta.el.ImportHandler.resolveClass(ImportHandler.java:109)
	at jakarta.servlet.jsp.el.ImportELResolver.getValue(ImportELResolver.java:62)
	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:123)
	at org.glassfish.expressly.parser.AstIdentifier.getValue(AstIdentifier.java:97)
	at org.glassfish.expressly.ValueExpressionImpl.getValue(ValueExpressionImpl.java:138)
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:925)
	at org.apache.jsp.test_jsp._jspService(test_jsp.java:1077)
`
So could some form of caching be considered here for a performance improvement?

### PR DESCRIPTION
**Pull request by aogburn**
fixes #245

### CODE REVIEW

**Comment by arjantijms** [comment]
Isn't that kind of caching already done by the `ImportHandler` in `jakarta.el.ImportHandler.resolveClassFor(String)`?

```java
    private Class<?> resolveClassFor(String className) {
        Class<?> c = classMap.get(className);
        if (c != null) {
            return c;
        }

        c = getClassFor(className);
        if (c != null) {
            checkModifiers(c.getModifiers());
            classMap.put(className, c);
        }

        return c;
    }
```

See https://github.com/jakartaee/expression-language/blob/master/api/src/main/java/jakarta/el/ImportHandler.java#L137

**Comment by arjantijms** [comment]
p.s. there's a few additional things to be said; 

* the Expression Language `ImportHandler` does not cache the `null` outcome, so that is difference with caching.
* The pages API already hints at providing the caching here via 
        " // A possible optimization is to set the ELClass
         // instance in an attribute map."
* The classes are ultimately fetched from the ContextClassloader (in the default case), and the `ImportHandler` instance is retrieved from the `ELContext`. So caching is per 'context'
* I don't know if `ImportELResolver` instances are automatically part of that context. Likely not, as otherwise the context would not have to be passed into the `getValue` etc methods.

We therefor have to give this a little more thought.

**Comment by aogburn** [comment]
Thanks @arjantijms.  This would need some null caching to improve performance on top of ImportHandler's current cache.  Attempting to cache the null class returns in the ImportHandler itself as in [this tomcat fix](https://github.com/apache/tomcat80/commit/63665340bb6fb123d93627cf4eac62dadd1545ab) from @markt-asf  did not help since it was limited to the scope of that context and it's ImportHandler instance.  So it was ultimately improved in Tomcat with this [specific fix](https://github.com/apache/tomcat80/commit/b69ed7e5f1bfd20ac09f8ea70e77731e1f1fcb44) to skip over the ImportHandler calls for such an attribute.

**Comment by markt-asf** [comment]
Closing as per comment on #245

**Pull request closed without merging**
