### PR TITLE
Remove snapshot versions of platform tck modules, use M1 versions from maven

### PR DESCRIPTION
**Pull request by alwin-joseph**

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
Note that M2 is about to be released as well.

**Comment by scottmarlow** [comment]
@arjantijms if we need a M2 release for the shared Platform TCK modules, we will definitely publish a m2 release but more likely we will have a { M2, M3, M4, M5, ... } as a lot of work remains to be done.  

The big work remaining is on the EE side of TCK work in terms of figuring out the automation part.

**Comment by alwin-joseph** [comment]
@markt-asf This PR uses M1 versions of platform TCK modules. Can you please merge this and follow https://github.com/jakartaee/pages/pull/261#issuecomment-2026751030 to generate the TCK bundle so https://github.com/jakartaee/specifications/pull/723 can proceed.

**Comment by alwin-joseph** [comment]
@arjantijms @markt-asf Can we please merge this so the TCK can be built from here.

**Pull request merged**
